version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  logstash:
    build:
      context: logstash/
    container_name: logstash
    environment:
      - path.config=/usr/share/logstash/pipeline
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    ports:
      - 5000:5000
      - 31311:31311
    networks:
      - esnet
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana
    environment:
      - server.name=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  esnet: